### ISSUE TITLE
another one clang build fail

### ISSUE THREAD

**Issue by fedya** [sahlberg/libiscsi#131]
[fedya@xgene libiscsi-1.11.0]$ make
make  all-recursive
make[1]: Entering directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0'
Making all in lib
make[2]: Entering directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0/lib'
Making all in doc
make[2]: Entering directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0/doc'
Making all in utils
make[2]: Entering directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0/utils'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0/utils'
Making all in test-tool
make[2]: Entering directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0/test-tool'
/usr/bin/clang -DHAVE_CONFIG_H -I. -I..  -I. -I../include "-D_U_=__attribute__((unused))" "-D_R_(A,B)=__attribute__((format(printf,A,B)))"  -Wall -W -Wshadow -Wstrict-prototypes -Wpointer-arith -Wcast-align -Wno-strict-aliasing -Werror -Wwrite-strings -O2 -g -c -o 0430_report_all_supported_ops.o 0430_report_all_supported_ops.c
0430_report_all_supported_ops.c:189:10: error: cast from 'char *' to 'struct scsi_command_descriptor *' increases required alignment from 1 to 4 [-Werror,-Wcast-align]
                desc = (struct scsi_command_descriptor *)((char *)desc +
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:1388: recipe for target '0430_report_all_supported_ops.o' failed
make[2]: *** [0430_report_all_supported_ops.o] Error 1
make[2]: Leaving directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0/test-tool'
Makefile:483: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/fedya/libiscsi/BUILD/libiscsi-1.11.0'
Makefile:370: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sahlberg** [comment]
clang on osx works in current master.
