### ISSUE TITLE
If built with gcc 4.9, iscsi-test-cu segfaults when it is invoked without a testname regexp

### ISSUE THREAD

**Issue by cvubrugier** [sahlberg/libiscsi#137]
I think that this issue is more a gcc bug than a bug in libiscsi but I open an issue here to gather your opinion.

I built libiscsi with gcc on Debian testing (Debian gcc version 4.9.1-11) and I experience a very strange crash when I invoke `iscsi-test-cu` without a testname regexp:

    $ ./iscsi-test-cu -i iqn.1998-01.com.vmware:esx1-1102c5da \
    -I iqn.1998-01.com.vmware:esx2-77a134a0 iscsi://10.21.58.53/iqn.1995-05.foo.bar:iscsi1/0
    Segmentation fault

What happens is that a `strdup()` of a NULL variable is performed. In the snippet below, the `else` path is taken even if `testname_re` is `NULL`:

```c
if (!testname_re) {
	family_re = strdup("*");
	suite_re = strdup("*");
	test_re = strdup("*");
} else {
	family_re = strdup(testname_re);
}
```
I have extracted the code from iscsi-test-cu that triggers the bug. You can find it there:
https://gist.github.com/cvubrugier/e2b72080ab344b9f1a15

I have tested with several gcc versions and only gcc 4.9 with `-O2` exhibit this bug (4.7 and 4.8 are OK). Moreover, passing the `-fno-strict-aliasing` flag to gcc 4.9 fixes the issue.

**Comment by sahlberg** [comment]
GCC 4.9 is mad.
If it fails because we are passing a char * to a const char * function,  GCC 4.9 is mad.
