### ISSUE TITLE
iscsi-perf is not packaged in RPM

### ISSUE THREAD

**Issue by mykaul** [sahlberg/libiscsi#143]
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/yanivk/rpmbuild/BUILDROOT/libiscsi-1.13.0-1.db47577.el7.centos.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/bin/iscsi-perf

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/bin/iscsi-perf

**Comment by sahlberg** [comment]
done,   thanks

**Comment by mykaul** [comment]
Verified:
Wrote: /home/yanivk/rpmbuild/SRPMS/libiscsi-1.13.0-1.6422fad.el7.centos.src.rpm
Wrote: /home/yanivk/rpmbuild/RPMS/x86_64/libiscsi-1.13.0-1.6422fad.el7.centos.x86_64.rpm
Wrote: /home/yanivk/rpmbuild/RPMS/x86_64/libiscsi-debuginfo-1.13.0-1.6422fad.el7.centos.x86_64.rpm
Wrote: /home/yanivk/rpmbuild/RPMS/x86_64/libiscsi-utils-1.13.0-1.6422fad.el7.centos.x86_64.rpm
Wrote: /home/yanivk/rpmbuild/RPMS/x86_64/libiscsi-devel-1.13.0-1.6422fad.el7.centos.x86_64.rpm
Wrote: /home/yanivk/rpmbuild/RPMS/x86_64/libiscsi-testsuite-1.13.0-1.6422fad.el7.centos.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.DRwzWr
+ umask 022
+ cd /home/yanivk/rpmbuild/BUILD
+ cd libiscsi-1.13.0
+ rm -rf /home/yanivk/rpmbuild/BUILDROOT/libiscsi-1.13.0-1.6422fad.el7.centos.x86_64
+ exit 0
Executing(--clean): /bin/sh -e /var/tmp/rpm-tmp.J0CqcH
+ umask 022
+ cd /home/yanivk/rpmbuild/BUILD
+ rm -rf libiscsi-1.13.0
+ exit 0
makerpms.sh: Done.
