### ISSUE TITLE
In master/trunk libiscsi opens lun 0 only.

### ISSUE THREAD

**Issue by redtex** [sahlberg/libiscsi#154]
In master/trunk - no matter what lun number I pass with command line, there is always opens lun 0.
But in master/tags/1.13.0 - it's ok.

**Comment by sahlberg** [comment]
Hmmm

I can not look at this until late tonight (it is morning now).

Can you test if this is reproduceable with the iscsi-inq command that is
built as part of libiscsi?
Syntax to run it is something like :     ./utils/iscsi-inq
iscsi://<ip-address>/<target-iqn-name>/<lun>

And see if it can access other LUNs than only LUN 0.


If so, can you bisect between 1.13 and current tip of master and see which
patch broke it?

**Comment by plieven** [comment]
Can you specifiy the exact command you use and the iSCSI URL you pass? I general we do not login to a specific LUN, we login to a target and then pass the LUN to each command we send to the target.

**Comment by redtex** [comment]
Hi !!!
Sorry for taking so long to answer - was absent on weekend....
About iscsi-inq - it connects, but it don't print lun number.

The command line I use:
 /usr/bin/kvm ..... -drive file=iscsi://192.168.107.23/iqn.2005-05.com.sdsys1:pool2t/136,if=none,id=drive-virtio0,cache=directsync,aio=native,detect-zeroes=on -device ....

What I have done - I've compiled several history points to determine which patch broke libiscsi, so:
1. https://github.com/sahlberg/libiscsi/commit/b03959dbb5dadca721b00b505ff4cb325ad94d70 including this commit and earlier qemu starts and connects to proper lun.
2. https://github.com/sahlberg/libiscsi/commit/15490a4c3e6a3b4c816448272f6e7a33fcf3162e including this commit and to the previously mentioned qemu don't start at all, with exit code 1
3. https://github.com/sahlberg/libiscsi/commit/a45094b7a7684cd0f859ea0707bfbd8d366a7937 including this commit and later qemu starts, but always connects to lun 0

**Comment by plieven** [comment]
iscsi_parse_url parses the LUN ID correctly from the URL you specified. As said before you connect to the target not to the LUN. I will check qemu code shortly.

**Comment by plieven** [comment]
qemu seems also to work fine.

**Comment by plieven** [comment]
Can you use git bisect to find the first bad commit please. I cannot reproduce your issue here.

**Comment by plieven** [comment]
Is there a ready to use appliace that provides and scst target? Or can you a target with a LUN > 0 that I can use for testing. Thanks.

**Comment by redtex** [comment]
the first bad commit I've wrote before - https://github.com/sahlberg/libiscsi/commit/15490a4c3e6a3b4c816448272f6e7a33fcf3162e after this commit qemu don't start at all

after tis commit https://github.com/sahlberg/libiscsi/commit/15490a4c3e6a3b4c816448272f6e7a33fcf3162e qemu starts, but connects only to lun0

I can give you access to scst target with lin > 0.

**Comment by plieven** [comment]
Please write me a PM to pl@kamp.de. Thanks

**Comment by redtex** [comment]
I wrote PM on given address.

**Comment by sahlberg** [comment]
Can not be reproduced and qemu uses lun!=0 all the time.
