### ISSUE TITLE
during sequential lun add/remove, i/o activity stops with error in VM 

### ISSUE THREAD

**Issue by redtex** [sahlberg/libiscsi#156]
Hi !

I use Proxmox hypervisor: libiscsi 1.13.0 with qemu 2.2.1 with centos 6 inside VM.
Centos 7 based storage with scst 3.0.2.

When I sequentially add/remove lun on storage, there is I/O error inside VM which results broken journal and readonly file system (ext 4).
This problem absent when I use open-iscsi.
Dump file here: http://owncloud.sdsys.ru/public.php?service=files&t=f5aee9402b36cc359b413ff6c9c87b65

**Comment by plieven** [comment]
The dump file is really difficult to read because it contains various connections and is incomplete. Please capture the complete sequence from qemu start until qemu terminates and grep just the TCP stream for a single connections. Ideally you capture on an otherwise empty host. Please also use the current master as only this contains the fix for the async messages that scst sends.

**Comment by redtex** [comment]
Hello.
Sorry, my bad, I've re-created two dumps.
http://owncloud.sdsys.ru/public.php?service=files&t=2d516281a0902baeed626562b5eaef63
http://owncloud.sdsys.ru/public.php?service=files&t=6942cd7d43e0c14c7154b23f6ede48aa
So, you should look at packet 5512 in dump_ro2.cap, packet 16771  in dump_ro3.cap
After those packets, I got in VM such error:

end_request: I/O error, dev vda, sector 30668480
Aborting journal on device dm-0-8.
EXT4-fs error (device dm-0): ext4_journal_start_sb: Detected aborted journal
EXT4-fs (dm-0): Remounting filesystem read-only

**Comment by redtex** [comment]
Hello.
Created dump with current master - situation absolutely the same, as with 1.13
see packet 9074 in following dump:
http://owncloud.sdsys.ru/public.php?service=files&t=786868c20dbe5817a5dd4160437a1005

**Comment by sahlberg** [comment]
None of these links work for me.

**Comment by plieven** [comment]
I had a look at the traces. What I do not understand are 2 things:

a) how can it happen that Qemu does communicate with different LUNs over one single TCP session.
I see communication from port 192.168.107.6 port 41894 to 192.168.107.23 port 3260, but there
are several LUNs accessed e.g. 0x54, 0x8c, 0x2c etc.

b) I see periodical Test Unit Ready commands. That is something that Qemu can only create at
Login time. There is no other way to generate TUR commands with virtio.

The I/O stalls when an Inquiry is send. However that is generated.

Can you verify that I can access the LUN on your target from remote. Then I can continue
debugging.

Thanks,
Peter

Am 13.04.2015 um 22:23 schrieb redtex:

**Comment by redtex** [comment]
Hi !
Sorry, all of links was unreachable because of VM failure, now it's all fine.
I've forwarded port 3260 to target.

**Comment by sahlberg** [comment]
dump_ro4.cap

There are two iscsi sessions in this capture.
One is from client source port 36177.
This traffic all looks like qemu+libiscsi.
For example, the lun is all the same on every command, as is a
qemu+liniscsi requirement,
second   if you look at the InitiatorTaskTag that is generated it is
originally a random number and then increments by one in every PDU.



Then you also have, from the same client, a second iSCSI session that comes
from port 41894.
This traffic does not look like libiscsi at all.
First of all it generates Inquiry and TestUnitReady commands, which
qemu+libiscsi does not use, except for the login phase.
Second, it accesses a lot of different LUNs,   which qemu+libiscsi can not
do. Qemu+libiscsi is one session per LUN, it can not share one session for
multiple LUNs.
And third, if you look at the InitiatorTaskTag you see a completely
different pattern in how it is incremented every PDU.
In this session it does not increment by one for each packet, instead the
most significant BYTE changes irregularly.
See packet 9070  ITT==0x3f000040   then the next PDU in packet 9073 has
ITT==0x15000040
This sequence of ITT is not generated by libiscsi    but this sequence does
match the pattern on how to change ITT between PDUs that the kernel
open-iscsi uses.
This basically looks like open-iscsi.



So in this case, packet 9074 does not look like libiscsi at all but rather
kernel open-iscsi.
Can you remove openiscsi completely from that host and ONLY access the LUNs
from libiscsi ?

You should never use both at the same time since if they access the same
LUN they will cause data-corruption for that LUN since
you basically will have two independent initiators that access the same
data but without any coordination between them.

**Comment by redtex** [comment]
Hi !
Sorry, you right - the open-isscsi was logged on....
I've turned off iscsid and re-created dump
http://owncloud.sdsys.ru/public.php?service=files&t=90c2740fa69c4b1100b3280d0a071187
after packet 3117 there is no writes.... and file system again falls in RO

**Comment by redtex** [comment]
Update:
I've run kvm with:
LIBISCSI_TCP_SYNCNT=2 LIBISCSI_DEBUG=6  /usr/bin/kvm .....  -drive file=iscsi://192.168.107.23/iqn.2005-0
5.com.sdsys1:pool2t/138.....
and got in stdout/stderr:

libiscsi:2 TCP_SYNCNT will be set to 2 on next socket creation
libiscsi:5 small allocation size is 256 byte
libiscsi:2 connecting to portal 192.168.107.23 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 SO_KEEPALIVE set to 1 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_KEEPCNT set to 3 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_KEEPINTVL set to 30 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_KEEPIDLE set to 30 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_SYNCNT set to 2 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_NODELAY set to 1 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 connection established (192.168.107.6:32785 -> 192.168.107.23) [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 login successful [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 SENSE KEY:UNIT_ATTENTION(6) ASCQ:BUS_RESET(0x2900) [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:6 smalloc free == SMALLOC_MAX_FREE [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:6 smalloc free == SMALLOC_MAX_FREE [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 BUSY [iqn.2005-05.com.sdsys1:pool2t]
kvm: iSCSI Busy (retry #1 in 0 ms): BUSY
libiscsi:1 TASK_SET_FULL [iqn.2005-05.com.sdsys1:pool2t]
kvm: iSCSI Failure: TASK_SET_FULL
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 TASK_SET_FULL [iqn.2005-05.com.sdsys1:pool2t]
kvm: iSCSI Failure: TASK_SET_FULL
^Cqemu: terminating on signal 2

**Comment by plieven** [comment]
That explains the I/O error. We simply don't handle TASK_SET_FULL in qemu (yet).
Can you provide a pcap trace of the condition below?

I wonder what the best way to handle TASK_SET_FULL messages is, Ronnie, Paolo?
We can tread it like BUSY, but this might not be enough?

I checked the specs after issuing a BUSY it is legal to return TASK_SET_FULL if at least
one command is in the queue.

CC'ing Paolo as he is also one of the iSCSI maintainers in Qemu.

Peter

Am 14.04.2015 um 18:21 schrieb redtex:

**Comment by plieven** [comment]
If you can compile Qemu on your own try the following experimental patch. Maybe it already solves your issue:

diff --git a/block/iscsi.c b/block/iscsi.c
index 0b6d3dd..ac14361 100644
--- a/block/iscsi.c
+++ b/block/iscsi.c
@@ -182,10 +182,10 @@ iscsi_co_generic_cb(struct iscsi_context *iscsi, int status,
                 iTask->do_retry = 1;
                 goto out;
             }
-            if (status == SCSI_STATUS_BUSY) {
+            if (status == SCSI_STATUS_BUSY || status == SCSI_STATUS_TASK_SET_FULL) {
                 unsigned retry_time =
                     exp_random(iscsi_retry_times[iTask->retries - 1]);
-                error_report("iSCSI Busy (retry #%u in %u ms): %s",
+                error_report("iSCSI Busy/TaskSetFull (retry #%u in %u ms): %s",
                              iTask->retries, retry_time,
                              iscsi_get_error(iscsi));
                 aio_timer_init(iTask->iscsilun->aio_context,

Peter

Am 14.04.2015 um 21:32 schrieb Peter Lieven:

**Comment by redtex** [comment]
Hi !
Have not tried your's experimental patch yet, but found another workaround:
I always used to use virtio-blk with qemu for disk devices, but after some googling and thinking, I've decided to try virtio-scsi. And this solves my problem:
libiscsi:2 TCP_SYNCNT will be set to 2 on next socket creation
libiscsi:5 small allocation size is 256 byte
libiscsi:2 connecting to portal 192.168.107.23 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 SO_KEEPALIVE set to 1 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_KEEPCNT set to 3 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_KEEPINTVL set to 30 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_KEEPIDLE set to 30 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_SYNCNT set to 2 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:3 TCP_NODELAY set to 1 [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 connection established (192.168.107.6:38610 -> 192.168.107.23) [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 login successful [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 SENSE KEY:UNIT_ATTENTION(6) ASCQ:BUS_RESET(0x2900) [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:6 smalloc free == SMALLOC_MAX_FREE [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:6 smalloc free == SMALLOC_MAX_FREE [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 BUSY [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 TASK_SET_FULL [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 BUSY [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:1 TASK_SET_FULL [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 Ignoring received iSCSI AsyncMsg/SCSI Async Event [iqn.2005-05.com.sdsys1:pool2t]
libiscsi:2 disconnected from portal 192.168.107.23 [iqn.2005-05.com.sdsys1:pool2t]

Here is no "kvm: iSCSI Failure: TASK_SET_FULL" messages, and no errors inside VM.

**Comment by sahlberg** [comment]
On Tue, Apr 14, 2015 at 2:19 PM, redtex <notifications@github.com> wrote:

> Hi !
> Have not tried your's experimental patch yet, but found another workaround:
> I always used to use virtio-blk with qemu for disk devices, but after some
> googling and thinking, I've decided to try virtio-scsi. And this solves my
> problem:
>

Ok, so the LUN 0 is no longer an issue. It was just open-iscsi polluting
the network traces?

Can you try Peters patch and see if it makes it work for the virtio-blk
case?
TASK_SET_FULL in this situation is very very unusual that a target will
generate, but we should be prepared to cope with it anyways.

Peter's patch looks obviously correct  but it would be nice to have it
verified.

**Comment by redtex** [comment]
Hi !
I think, I can verify qemu patches soon - during one or two work days.
Lun 0 is still issue. Now, it's fixed qemu behavior in case of TASK_SET_FULL message, but not libiscsi lun 0 problem.
