### ISSUE TITLE
makerpms failure - iscsi-multipath.c:47:29: fatal error: iscsi-multipath.h: No such file or directory

### ISSUE THREAD

**Issue by mykaul** [sahlberg/libiscsi#169]
make[2]: Entering directory `/home/yanivk/rpmbuild/BUILD/libiscsi-1.14.0/test-tool'
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../include "-D_U_=__attribute__((unused)) " "-D_R_(A,B)=__attribute__((format(printf,A,B)))"  -Wall -W -Wshadow -Wstrict-prototypes -Wpointer-arith -Wcast-align -Wno-strict-aliasing -Werror -Wwrite-strings -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c -o iscsi-test-cu.o iscsi-test-cu.c
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../include "-D_U_=__attribute__((unused)) " "-D_R_(A,B)=__attribute__((format(printf,A,B)))"  -Wall -W -Wshadow -Wstrict-prototypes -Wpointer-arith -Wcast-align -Wno-strict-aliasing -Werror -Wwrite-strings -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c -o iscsi-support.o iscsi-support.c
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../include "-D_U_=__attribute__((unused)) " "-D_R_(A,B)=__attribute__((format(printf,A,B)))"  -Wall -W -Wshadow -Wstrict-prototypes -Wpointer-arith -Wcast-align -Wno-strict-aliasing -Werror -Wwrite-strings -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c -o iscsi-multipath.o iscsi-multipath.c
gcc -DHAVE_CONFIG_H -I. -I..  -I. -I./../include "-D_U_=__attribute__((unused)) " "-D_R_(A,B)=__attribute__((format(printf,A,B)))"  -Wall -W -Wshadow -Wstrict-prototypes -Wpointer-arith -Wcast-align -Wno-strict-aliasing -Werror -Wwrite-strings -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c -o test_compareandwrite_simple.o test_compareandwrite_simple.c
iscsi-multipath.c:47:29: fatal error: iscsi-multipath.h: No such file or directory
 #include "iscsi-multipath.h"
                             ^
compilation terminated.
iscsi-test-cu.c:54:29: fatal error: iscsi-multipath.h: No such file or directory
 #include "iscsi-multipath.h"
                             ^
compilation terminated.

Last commit:
commit 3f73f00b25eca08f35504bcc802f6e8fe404e49a
Merge: a8e4268 ff7a733
Author: Ronnie Sahlberg <ronniesahlberg@gmail.com>
Date:   Tue Jun 2 19:39:02 2015 -0700

    Merge pull request #168 from rodrigc/fix1
    
    test_reserve6_target_cold_reset: fix login parameters

**Comment by sahlberg** [comment]
Fixed.

Thanks.

**Comment by mykaul** [comment]
Verified - thanks.
