### ISSUE TITLE
Difficulty iscsi-test-cu connecting to SAN after configuring the initiators and shares.

### ISSUE THREAD

**Issue by jakeaidan** [sahlberg/libiscsi#179]
I'm having trouble getting iscsi-test-cu to connect to the SAN iscsi share.

I can get my ubuntu client to discover and attach the iscsi share, format it, write to it...so the configuration of the LUN seems adequate.

I have added both the default iscsi initiators to the SAN config 
iqn.2007-10.com.github:sahlberg:libiscsi:iscsi-test
iqn.2007-10.com.github:sahlberg:libiscsi:iscsi-test-2
and added them to the target lun.   Configured the LUN to attach to all initiators.

confirmed the LUN number = 1 with iscsi-ls

Then I run this command as root
iscsi-test-cu -t=LINUX.Write10 iscsi://10.145.137.117:3260/iqn.1986-03.com.sun:02:e3d302ca-1cba-ca84-e67b-c57cd86387b3/1

and get the following
    [FAILED] INQUIRY command failed with sense. (null)
    [FAILED] INQUIRY command failed with sense. (null)
Failed to read Block Device Characteristics page
    [SKIPPED] REPORT_SUPPORTED_OPCODES is not implemented.

     CUnit - A unit testing framework for C - Version 2.1-2
     http://cunit.sourceforge.net/

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites      0      0    n/a      0        0
               tests      0      0      0      0        0
             asserts      0      0      0      0      n/a

Elapsed time =    0.000 seconds
Tests completed with return value: 0

Is this likely a problem with my SAN?   As I said, I can use standard iscsi mount, write, read, workflows using open-iscsi, but I'm having trouble getting the iscsi-test-cu tool to work.

**Comment by sahlberg** [comment]
I think it might be the options parser I use that is sensitive.
It takes a '=' only after long arguments, but not after short arguments.

So it is either
 -t LINUX.Write10
or
 --test=LINUX.Write10

Try that.

**Comment by jakeaidan** [comment]
Thank you, I'm usually not this dense!

**Comment by sitsofe** [comment]
@jakeaidan: Can this issue be closed?

**Comment by jakeaidan** [comment]
Yes!  Thank you for your help!

Date: Wed, 2 Dec 2015 10:58:36 -0800
