### ISSUE TITLE
Qemu + libiscsi = lun 0 only access

### ISSUE THREAD

**Issue by redtex** [sahlberg/libiscsi#183]
I'm using Qemu v.2.2.1 with libiscsi 1.13 as initiator and SCST 3.1 as target and it works.
Earlier I've opened issue #154, but it was closed as "unpronounceable".
The issue nature is - when I try to use libiscsi > 1.13 with QEMU - no matter which lun number I pass, it always connects to lun 0.
So, for now, I've repeated my tests and get same result - qemu opens lun 0.
Here, some tests.
First:
 ./iscsi-inq iscsi://192.168.21.29/iqn.2005-05.com.sdsys:pool400g/0
Peripheral Qualifier:CONNECTED
Peripheral Device Type:DIRECT_ACCESS
........
Vendor:SCST_FIO
Product:dummy22964
.......
So yes, lun 0 has underluying device "SCST_FIO dummy22964" - its seems to connect to right lun.

Second:
 ./iscsi-inq iscsi://192.168.21.29/iqn.2005-05.com.sdsys:pool400g/1
Peripheral Qualifier:CONNECTED
Peripheral Device Type:DIRECT_ACCESS
....
Vendor:SCST_BIO
Product:v3075215056
....
It's all right again - lun 1 has underluying device "SCST_BIO v3075215056".

Now, I try to run qemu with libiscsi 1.13:
Command line is:
/usr/bin/kvm .......  -drive file=iscsi://192.168.21.29/iqn.2005-05.com.sdsys:pool400g/1 .....

![good-lun](https://cloud.githubusercontent.com/assets/8180104/10125411/6c2d7be6-657b-11e5-8779-1f3a7229f14c.png)

It's seems to be fine, virtio_scsi has "SCST_BIO v3075215056" which belongs to lun 1.

But when I switch to libiscsi 1.15 with same command line, as before, I have:
![bad-lun](https://cloud.githubusercontent.com/assets/8180104/10125413/c01821ca-657b-11e5-819e-9e3003918eea.png)
Now, virtio_scsi has "SCST_FIO dummy22964" which belongs to lun 0.

So, issue is reproducible.

I've bisect between 1.13 and 1.14 and discovered, that:
1. https://github.com/sahlberg/libiscsi/commit/b03959dbb5dadca721b00b505ff4cb325ad94d70 including this commit and earlier qemu starts and connects to proper lun.
2. https://github.com/sahlberg/libiscsi/commit/15490a4c3e6a3b4c816448272f6e7a33fcf3162e including this commit and to the previously mentioned qemu don't start at all, with Segmentation Fault.
3. https://github.com/sahlberg/libiscsi/commit/a45094b7a7684cd0f859ea0707bfbd8d366a7937 including this commit and later qemu starts, but always connects to lun 0

**Comment by sahlberg** [comment]
You have to recompile qemu against the new version of libiscsi

**Comment by redtex** [comment]
Hi !!!
Thank you for the fast answer.
Do you mean, that during qemu compile process there are used some header files from libiscsi ?
Or I have to use just more recent version of qemu ?

**Comment by sahlberg** [comment]
On Tue, Sep 29, 2015 at 6:15 AM, redtex <notifications@github.com> wrote:

> Hi !!!
> Thank you for the fast answer.
> Do you mean, that during qemu compile process there are used some header
> files from libiscsi ?
>

Yes.  It uses libiscsi header files during the compile and there was an
unfortunate abi bteakage in 1.13.

Compile and install the latest version of libiscsi, then re-compile qemu
from scratch and it should all work.

**Comment by redtex** [comment]
Thank you !
