### ISSUE TITLE
Can't get iscsi-inq tool to properly log-in with CHAP or Mutual CHAP

### ISSUE THREAD

**Issue by bramklg** [sahlberg/libiscsi#189]
I'm trying to use `iscsi-inq` tool to verify if specified iscsi settings are correct. This works for targets that don't require authentication but fails for targets that require CHAP or Mutual CHAP. I was first using version 1.4.0-3 that comes with ubuntu 14.04 but currently i'm testing against the master branch.

My ISCSI target is a freenas server that displays the following in the logs when trying to log-in:

> Feb  3 09:50:14 freenas ctld[94005]: 192.168.8.179 (iqn.2007-10.com.github:sahlberg:libiscsi:iscsi-inq): CHAP authentication failed for user "bram"
> Feb  3 09:50:14 freenas ctld[92923]: child process 94005 terminated with exit status 1

I'm certain the username and password are correct. When I set-up an iscsi connection using `iscsiadm` everything works as expected. Am I doing something wrong or is this a bug in the tool? 

This is the configuration of my iscsi target:
>host: 192.168.8.106
>target: iqn.2005-10.org.freenas.ctl:target2
>lun: 0
>Auth: CHAP
>User: bram
>Pass: test123456789

I'm using the following command to test if the connection settings are valid or not:
`iscsi-inq --debug iscsi://bram%test123456789@192.168.8.106:3260/iqn.2005-10.org.freenas.ctl:target2/0`

Executing this command gives the following output:
>libiscsi:1 Failed to log in to target. Status: Authentication failure(513) [iqn.2005-10.org.freenas.ctl:target2]
>Login Failed. Failed to log in to target. Status: Authentication failure(513)

If I execute the tool to a target without authentication requirements iscsi-inq correctly displays information about the target / connection.

**Comment by sitsofe** [comment]
I think I've seen this too and the problem might have linked to if the target returned CHAP responses in base64 or binary (but I could be wrong).

**Comment by sahlberg** [comment]
On Wed, Feb 3, 2016 at 1:01 AM, bramklg <notifications@github.com> wrote:

> I'm trying to use iscsi-inq tool to verify if specified iscsi settings
> are correct This works for targets that don't require authentication but
> fails for targets that require CHAP or Mutual CHAP I was first using
> version 140-3 that comes with ubuntu 1404 but currently i'm testing against
> the master branch
>
> My ISCSI target is a freenas server that displays the following in the
> logs when trying to log-in:
>
> Feb 3 09:50:14 freenas ctld[94005]: 1921688179
> (iqn2007-10comgithub:sahlberg:libiscsi:iscsi-inq): CHAP authentication
> failed for user "bram"
> Feb 3 09:50:14 freenas ctld[92923]: child process 94005 terminated with
> exit status 1
>
> I'm certain the username and password are correct When I set-up an iscsi
> connection using iscsiadm everything works as expected Am I doing
> something wrong or is this a bug in the tool?
>

If  iscsiadm works but iscsi-inq does not then it is most likely a bug in
libiscsi.

Can you collect a wireshark trace when you authenticate successfully with
iscsiadm  and a second trace when you fail with iscsi-inq and send to me?
That should show what the differences might be.

**Comment by bramklg** [comment]
Thanks for the responses. Attached are two pcap files, one from iscsiadm and one from iscsi-inq.

[iscsi_login_wireshark.zip](https://github.com/sahlberg/libiscsi/files/116992/iscsi_login_wireshark.zip)

**Comment by bramklg** [comment]
Little bump .. anything else we can do on our side?

**Comment by sahlberg** [comment]
This should be fixed in current master. Can you retest and verify?

**Comment by bramklg** [comment]
Yes, works!
