### ISSUE TITLE
Abort task TMF requests are sent to target for locally cancelled PDUs

### ISSUE THREAD

**Issue by ddiss** [sahlberg/libiscsi#192]
I'm working on a libiscsi test that queues a bunch of WRITE10 PDUs via iscsi_scsi_command_async(), and then proceeds to abort them via iscsi_task_mgmt_abort_task_async(). This is all done before entering the iscsi_service() loop.

When executed, the WRITE10 PDUs don't appear on the network (they're cancelled locally), but all ABORT TASK TMF requests _are_ sent to the target (with a ReferencedTaskTag that the target has never seen).

This strange behaviour is due to iscsi_task_mgmt_abort_task_async()'s call to iscsi_scsi_cancel_task() (which cancels the locally queued task) and subsequent iscsi_task_mgmt_async() invocation, which dispatches the TMF request for the locally cancelled task.

This bug could easily be resolved by avoiding the iscsi_task_mgmt_async() invocation if iscsi_scsi_cancel_task() returns zero. However, I'd like some guidance on how the TMF task's callback should be handled in such a case - should we simply invoke pdu->callback(response=Function complete,...), or would it be better to use a special response value (outside the 8bit TMF response range) that indicates local cancellation.

Note: this bug appears to also affect iscsi_task_mgmt_abort_task_sync().

**Comment by ddiss** [comment]
Local cancellation is already detectable by the caller via the status=SCSI_STATUS_CANCELLED callback for the referenced (aborted) task, so I'm leaning towards just using tmf_pdu->callback(response=Function complete,...).

**Comment by sahlberg** [comment]
Yeah, that looks like a bug.

We either need to change iscsi_scsi_cancel_task() to return more
information.
So that we can distinguish between
* failure
* was removed from outqueue (i.e. has not yet been sent)
* was removed from waitqueue

Or we need a new helper function where we can ask "has this task been
written to the socket or not".

Since we currently only call it from two places, and never inspect the
return value, the first option is probably best.


On Mon, Mar 14, 2016 at 10:37 AM, David Disseldorp <notifications@github.com
> wrote:

> Local cancellation is already detectable by the caller via the
> status=SCSI_STATUS_CANCELLED callback for the referenced (aborted) task, so
> I'm leaning towards just using tmf_pdu->callback(response=Function
> complete,...).
>

That is a bit too subtle I think ot look at the status.
I think it is better to teach iscsi_scsi_cancel_task() to return how/what
was canceled.
And if iscsi_scsi_cancel_task() said it was cancelled locally (i.e. removed
from outqueue)
then just teach iscsi_task_mgmt_abort_task_async to invoke the callback
immediately.

**Comment by sahlberg** [comment]
On Mon, Mar 14, 2016 at 10:09 AM, David Disseldorp
<notifications@github.com> wrote:
> I'm working on a libiscsi test that queues a bunch of WRITE10 PDUs via
> iscsi_scsi_command_async(), and then proceeds to abort them via
> iscsi_task_mgmt_abort_task_async(). This is all done before entering the
> iscsi_service() loop.
>
> When executed, the WRITE10 PDUs don't appear on the network (they're
> cancelled locally), but all ABORT TASK TMF requests are sent to the target
> (with a ReferencedTaskTag that the target has never seen).
>
> This strange behaviour is due to iscsi_task_mgmt_abort_task_async()'s call
> to iscsi_scsi_cancel_task() (which cancels the locally queued task) and
> subsequent iscsi_task_mgmt_async() invocation, which dispatches the TMF
> request for the locally cancelled task.
>
> This bug could easily be resolved by avoiding the iscsi_task_mgmt_async()
> invocation if iscsi_scsi_cancel_task() returns zero. However, I'd like some
> guidance on how the TMF task's callback should be handled in such a case -
> should a new we simply invoke pdu->callback(response=Function complete,...),
> or would it be better to use a special response value (outside the 8bit TMF
> response range) that indicates local cancellation.

I think:
Just make it possible for iscsi_task_mgmt_abort_task_async() to know
whether or not the task was cancelled from the outqueue or not.
Tasks that are on the outqueue have not yet been written to the socket
so here we can avoid sending the task mgmt command to the target.
Tasks that are on the waitqueue have been written to the socket so
here we must send the task mgmt command to the target.

Then IF teh task was cancelled locally from the outqueue, then
iscsi_task_mgmt_abort_task_async can just invoke its callback with
completion immediately and skip calling iscsi_task_mgmt_async.


Something like
int
iscsi_task_mgmt_abort_task_async(struct iscsi_context *iscsi,
     struct scsi_task *task,
     iscsi_command_cb cb, void *private_data)
{
 ret = iscsi_scsi_cancel_task(iscsi, task);

 if (ret == cancelled-from-outqueue) {
   cp(... success...)
   return 0;
 }

return iscsi_task_mgmt_async(iscsi,
     task->lun, ISCSI_TM_ABORT_TASK,
     task->itt, task->cmdsn,
     cb, private_data);
}

**Comment by ddiss** [comment]
Actually, if the local cancellation is performed then we still end up with a gap in the CmdSN window, which means that all trailing PDUs in the queue, corresponding scsi_tasks and the session CmdSN values need to be adjusted.
The simplest (and IMO cleanest) solution for now is to just drop the local cancellation logic from the ABORT TASK codepath.

**Comment by ddiss** [comment]
The fix for this has been upstream for some time... closing.

commit c38a8c1d9a6f71e13f9933956f7c0d4db6792360
Author: David Disseldorp <ddiss@suse.de>
Date:   Tue Mar 22 17:10:43 2016 +0100

    task_mgmt: don't cancel local PDUs on ABORT TASK
