### ISSUE TITLE
Test write atomic 16 simple

### ISSUE THREAD

**Issue by di98jgu** [sahlberg/libiscsi#200]
Atomic aligment in block limits VPD page is not respected then
writing to the end of the logical unit [SBC-4] [1] p. 326 table 249. 

For a unit there aligment matters this test will fail.

[1]: "SCSI Block Commands – 4 (SBC-4) (1 Sep 2015) T10/BSR INCITS 506, Revision 8"

**Comment by sahlberg** [comment]
Thanks. Fixed in :
 678d70eb6895f8e0e01198cb8251a4d56b136849
