### ISSUE TITLE
Initializing structs with { 0 }

### ISSUE THREAD

**Issue by di98jgu** [sahlberg/libiscsi#201]
Initializing structs with { 0 } like
"struct my_struct = { 0 }"
throws compiler errors on some systems. It would be
nice if the structs was initialized the explicit way with
a 0 for every field.

**Comment by sitsofe** [comment]
There is a pull request #199 that works around this.

**Comment by sahlberg** [comment]
Merged. Thanks.

In these cases where we just initialize to 0, memset() might be  better alternative in the sense that we don't have to update any initializers if/when the structure changes.
