### ISSUE TITLE
Lost in refactoring...

### ISSUE THREAD

**Issue by di98jgu** [sahlberg/libiscsi#212]
Hey...

The function pointer _local_iscsi_queue_pdu_ is no longer called. This pointer is set by at least test suite sanitize and iSCSIcmdsn.

The reason is by calling iscsi->t->queue_pdu(...) in instead of iscsi_queue_pdu(...) in the lib functions the local queue is never called. Since the pointer real_iscsi_queue_pdu is replaced by t->queue_pdu in struct iscsi_context one can call t->queue from the function iscsi_queue_pdu(...). Very neat, I like the use of context. 

I tried this by rolling back changes done to the mechanics of iscsi_queue_pdu and it worked just fine. I do not know if this works for iser. I suppose primary function iscsi_queue_pdu(...) should not be in socket.c as before since this location is one of the two trouser legs for the t→queue_pdu(...) function.

Since I feel my grasp of C and libiscsi is bit slippery I drop this as an issue and not as a pull request. 

Thanks!
// JG

**Comment by sahlberg** [comment]
Sorry about that.

Should fixed now in :
commit 37507c994a69415405d89711c56e1f0e4164a456
Author: Ronnie Sahlberg <ronniesahlberg@gmail.com>
Date:   Mon Jul 11 18:37:25 2016 -0700

    Add back iscsi_queue_pdu
    
    We need a public symbol for iscsi_queue_pdu. This is now just a
    simple wrapper around iscsi->t->queue_pdu
    
    https://github.com/sahlberg/libiscsi/issues/212
    
    Signed-off-by: Ronnie Sahlberg <ronniesahlberg@gmail.com>

**Comment by di98jgu** [comment]
Hey

Confirmed, everything is back on track. I will review my scoreboard.

On a side note is real_iscsi_queue_pdu needed? 

One nice side effect of iser is that this all global function pointer is no longer needed. The struct iscsi_context already contains the function pointer.

Thanks, great!
// JG
