### ISSUE TITLE
can libiscsi be used on Qemu iscsi support ?

### ISSUE THREAD

**Issue by PopoBear** [sahlberg/libiscsi#228]
Since Open-iscsi is too large and some package just want to implement iscsi-client function.

can it used on Qemu ?

when qemu ./configure --enable-libiscsi

**Comment by PopoBear** [comment]
the answer .....

#194 
#183 
#156

**Comment by sahlberg** [comment]
Yes, it is already built into qemu.

As it avoids some data copy and context switches, it also provides
significantly higher performance than open iscsi.


http://www.snia.org/sites/default/files/SDC/2016/presentations/storage_networking/Shterman-Grimberg_Greenberg_Performance%20Implications%20Libiscsi_%20RDMA_V6.pdf
