### ISSUE TITLE
iscsi_full_connect_sync can return positive numbers on failure

### ISSUE THREAD

**Issue by sitsofe** [sahlberg/libiscsi#235]
Description of the problem:
While trying to log into a target which was missing libiscsi's ACL I found that `iscsi_full_connect_sync()` would return a positive (non-zero) number which is different to the comment in the header file.

Step to reproduce:
1. Create a target that has no ACLs (thus disallowing any initiator from logging in).
2. Create a program that uses libiscsi's iscsi_full_connect_sync e.g. it does something like:
```C
        new_context = iscsi_create_context(initiator);
        iscsi_url = iscsi_parse_full_url(new_context, url);
        iscsi_set_session_type(new_context, ISCSI_SESSION_NORMAL);
        iscsi_set_header_digest(new_context, header_digest);
        iscsi_set_reconnect_max_retries(new_context, 0);
        ret = iscsi_full_connect_sync(new_context, iscsi_url->portal,
                        iscsi_url->lun);
        printf("ret=%d\n", ret);
```

Expected result:
For ret to be less than 0 because the header file (https://github.com/sahlberg/libiscsi/blob/1.18.0/include/iscsi.h#L452 ) says this:
```
 * Returns:
 *  0 if the cconnect was successful.
 * <0 if there was an error.
```

Actual result:
ret returns 251658241.

How reproducible is the issue?
It is reproducible every time.

Additional information:
Perhaps the header comment should be updated to just say non-zero on error?

Version information:
libiscsi 9f4f6f85d01b4520ef07a5806ec12a239cf6a6ee
Ubuntu 16.04.1 x86_64

**Comment by plieven** [comment]
oops, actually that value is 0xF000001 which is SCSI_STATUS_ERROR.

i think we have to fix the sync calls to return -status or -1 in case of error. @sahlberg?

**Comment by sahlberg** [comment]
Ouch.
Yeah, lets just return -1.

**Comment by plieven** [comment]
send pull request #236

**Comment by sahlberg** [comment]
I have merged the fix.
