### ISSUE TITLE
Can't run make all in test-tool directory

### ISSUE THREAD

**Issue by doubleyuyu** [sahlberg/libiscsi#245]
How to generate  the binary file: iscsi-test?
I try to run make all in test-tool, but get 
"make: Nothing to be done for `all'."

**Comment by sitsofe** [comment]
@doubleyuyu This might be better asked on the mailing list but for starters have you got libcunit installed and if so does configure find it as mentioned in the README - https://github.com/sahlberg/libiscsi/blob/1.18.0/README#L131 ?

**Comment by doubleyuyu** [comment]
Thank you! Install libcunit and then reconfigure solved my problem.
