### ISSUE TITLE
coredump

### ISSUE THREAD

**Issue by rabishaw** [sahlberg/libiscsi#247]
(gdb) bt
#0  0x00007f0dbc665888 in _int_free () from /lib64/libc.so.6
#1  0x0000000000c39e28 in iscsi_free (ptr=0x7f0d7400b5a0, iscsi=0x7f0d740104b0) at init.c:104
#2  iscsi_sfree (iscsi=0x7f0d740104b0, ptr=0x7f0d7400b5a0) at init.c:137
#3  0x0000000000c39ffc in iscsi_destroy_context (iscsi=0x7f0d740104b0) at init.c:364
#4  0x0000000000c3a0fe in iscsi_destroy_context (iscsi=0x7f0d740008c0) at init.c:392
#5  0x0000000000b6b962 in Rainfinity::IScsi::Initiator::destroy (this=0x7f0db919acc0) at Initiator.cpp:180
#6  0x0000000000b6d366 in Rainfinity::IScsi::Initiator::clear (this=this@entry=0x7f0db919acc0, full=full@entry=true) at Initiator.cpp:1029
#7  0x000000000047f632 in Rainfinity::IScsi::Initiator::~Initiator (this=0x7f0db919acc0, __in_chrg=<optimized out>)
    at /home/shawr3/source/CTA/common/include/IScsi/Initiator.h:38
#8  Rainfinity::FileManagement::IScsiConnector::read_thread (this=0x39095a0) at IScsiConnector.cpp:488
#9  0x00007f0dbcf6e650 in ?? () from /usr/lib64/libstdc++.so.6
#10 0x00007f0dc0be50a4 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f0dbc6d202d in clone () from /lib64/libc.so.6
(gdb)

**Comment by sahlberg** [comment]
Libiscsi does is not threads safe and can not be used safely used in a multithreaded app.

It would not be very hard to add but I have no near term plans to add this as it is rather intended to be used in event driven designs.

For now, you can either make sure that you only call libiscsi from one single thread, or if you want to use multiple threads, you can use a dedicated iscsi context for each thread.

Even if you limit to just use a single thread for all libiscsi use, that should be fine performance wise as long as you use the async interface. The async interface can easily keep a 10GbE link saturated from a single thread/core.
