### ISSUE TITLE
error when building with gcc7

### ISSUE THREAD

**Issue by plusky** [sahlberg/libiscsi#248]
When building on openSUSE Tumbleweed, with gcc7 enabled, following occurs:
```
[   70s] iscsi-support.c: In function 'populate_ident_tgt_desc':
[   70s] iscsi-support.c:2929:36: error: this statement may fall through [-Werror=implicit-fallthrough=]
[   70s]                                  if (prev_type <= desig->designator_type) {
[   70s]                                     ^
[   70s] iscsi-support.c:2933:25: note: here
[   70s]                          default:
[   70s]                          ^~~~~~~
```

[build log](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:Gcc7/libiscsi/standard/x86_64)

**Comment by sahlberg** [comment]
Thanks,  I fixed this warning in 854e37aab7d7d2093a0a6620a3257b8f2a1d405c

We actually don't need to default:continue here as we are at the end of the switch/loop anyway
and can just drop the default arm and drop down to the end of the loop block.
