### ISSUE TITLE
How to use libiscsi via libvirt?

### ISSUE THREAD

**Issue by clicx** [sahlberg/libiscsi#255]
for iSCSI and iSER? are those supported by libvirt? I mean not pass though kernel module.

**Comment by sahlberg** [comment]
Hi,

I am pretty sure iSCSI via libiscsi is supported in current libvirt master
but I am certain that iSER via libiscsi is not (yet).


I don't know how to use libiscsi via libvirt, that is a question better
asked on the libvirt mailinglist.


regards
ronnie sahlberg

**Comment by clicx** [comment]
Thanks, I made successful to create vm via iSCSI by referring the help here:
https://www.suse.com/documentation/sles-12/book_virt/data/cha_qemu_running_devices.html
But I cloud't do it via iSER.

**Comment by sahlberg** [comment]
iSER support would be great in libvirt considering the significant
performance boost it provides :
https://www.snia.org/sites/default/files/SDC/2016/presentations/storage_networking/Shterman-Grimberg_Greenberg_Performance%20Implications%20Libiscsi_%20RDMA_V6.pdf

(those are tests with QEMU/KVM + libiscsi iSER)

To get iSER support in libvirt, you need to petition the libvirt folks to
add it.
I can not help there.


regards
ronnie sahlberg

**Comment by sitsofe** [comment]
@clicx you would be better off asking the libvirt project this directly (e.g. via https://libvirt.org/contact.html )...

**Comment by sahlberg** [comment]
Closing as this is not a libiscsi issue but a future feature request for the libvirt project.

libiscsi supports iSER today but has no influence over what other dependent projects do or their roadmaps.
