### ISSUE TITLE
how to always connect to a server even if server unavailable

### ISSUE THREAD

**Issue by clicx** [sahlberg/libiscsi#264]
I tried this,  but second connect don't start.

void connect_callback(struct iscsi_context *iscsi, int status, void *command_data, void *private_data)
{
        int i;
      
        printf("connect callback, %d\r\n", status);
        if(!status)
        {
                iscsi_login_async(iscsi, login_callback, private_data);
        }
        else
        {
                printf("connect error %d \r\n", status);
                //iscsi_disconnect(iscsi);
                if (iscsi_connect_async(iscsi, "xxx.xxx.xxx.xxx", connect_callback, private_data) != 0) 
                {
                        printf("iscsi_connect failed : %s\n", iscsi_get_error(iscsi));
                        return err_transport_fault;
                }
        }
}

**Comment by sahlberg** [comment]
Hmm. invoking a new connection from the current connect callback. I don't know if that would work.
(feels like undocumented behavior territory).

What happens if you just set a global variable and then exit back you tour event loop and then try the iscsi_connect_async() from there ?

**Comment by sitsofe** [comment]
@clicx did you try @sahlberg's suggestion and can this issue be closed?

**Comment by clicx** [comment]
Yes, I have made it working.
