### ISSUE TITLE
gcc8 warnings

### ISSUE THREAD

**Issue by crobinso** [sahlberg/libiscsi#266]
There's some compiler warnings with libiscsi and gcc8. I'm using gcc-8.0.1-0.20.fc28.x86_64 from Fedora 28

prog_reconnect_timeout.c:333:2: warning: ‘strncpy’ output may be truncated copying 255 bytes from a string of length 255 [-Wstringop-truncation]
  strncpy(state.portal, iscsi_url->portal, MAX_STRING_SIZE);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../lib/connect.c:435:2: warning: ‘strncpy’ output may be truncated copying 255 bytes from a string of length 255 [-Wstringop-truncation]
  strncpy(iscsi->portal,old_iscsi->portal,MAX_STRING_SIZE);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/connect.c:437:2: warning: ‘strncpy’ output may be truncated copying 255 bytes from a string of length 255 [-Wstringop-truncation]
  strncpy(iscsi->bind_interfaces,old_iscsi->bind_interfaces,MAX_STRING_SIZE);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/logging.c: In function ‘iscsi_log_message’:
../lib/logging.c:78:31: warning: ‘ [’ directive output may be truncated writing 2 bytes into a region of size between 1 and 1024 [-Wformat-truncation=]
   snprintf(message2, 1024, "%s [%s]", message, iscsi->target_name);
                               ^~
../lib/logging.c:78:3: note: ‘snprintf’ output between 4 and 1282 bytes into a destination of size 1024
   snprintf(message2, 1024, "%s [%s]", message, iscsi->target_name);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../lib/scsi-lowlevel.c: In function ‘scsi_maintenancein_datain_getfullsize’:
../lib/scsi-lowlevel.c:1055:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
   switch (scsi_report_supported_opcodes_options(task)) {
   ^~~~~~
../lib/scsi-lowlevel.c:1064:2: note: here
  default:
  ^~~~~~~

**Comment by sitsofe** [comment]
@crobinso is this fixed by #274 ?

**Comment by crobinso** [comment]
Yes it appears so, thanks for checking
