### ISSUE TITLE
Writesame of length max_ws_len should not expect failure.

### ISSUE THREAD

**Issue by SexyC** [sahlberg/libiscsi#270]
According to the logic below.  inq->max_ws_len is got from block limits query.
https://github.com/sahlberg/libiscsi/blob/36548b46692367d2372eb873195b0f47c03daa0e/lib/scsi-lowlevel.c#L1521

According to the spec sbc4r15, max_ws_len should be the maximum number of blocks that target claims to support writesame.
>A MAXIMUM WRITE SAME LENGTH field set to a non-zero value indicates the maximum number of contiguous logical blocks that the device server allows to be unmapped or written in a single WRITE SAME command.

So I think the following logic in https://github.com/sahlberg/libiscsi/blob/master/test-tool/test_writesame10_0blocks.c#L56 should be changed to 
```c
if (inq_bl->max_ws_len > 0 && num_blocks > inq_bl->max_ws_len) {
    WRITESAME10(sd, 0, block_size, 0, 0, 0, 0, 0, scratch,
                        EXPECT_INVALID_FIELD_IN_CDB);
}
```
because when max_ws_len == num_blocks, the target support writesame to the entire LUN. We should expect the writesame10 operation succeed.

**Comment by sitsofe** [comment]
@SexyC can you check over https://github.com/sahlberg/libiscsi/commit/b908bdeb99c2cc40e6f4ece6a093f3de2afa8fd7 and see what you think?

**Comment by sitsofe** [comment]
@SexyC sorry I misread your patch - you're saying it's an off by one error right? If so I see your point and I think you're right (although I had only a cursory glance). Could you turn this into a proper pull request and fix up test_writesame16_0blocks.c too?

**Comment by SexyC** [comment]
@sitsofe Created a pull request. Please help review. Thanks! https://github.com/sahlberg/libiscsi/pull/271

**Comment by sitsofe** [comment]
@SexyC Thanks for your diligence! I did look over the pr but I didn't need to comment before Ronnie pulled it in :-)

Given that it's been applied, do you think you could close this issue?
