### ISSUE TITLE
test-tool: support low level PDU manipulation

### ISSUE THREAD

**Issue by ddiss** [sahlberg/libiscsi#297]
I'm currently working on a SendTargets test and would like to be able to modify some low-level PDU attributes, such as data segment, ISCSI_PDU_TEXT_FINAL, etc.
This doesn't appear to be possible using existing helpers, so I think it'd make sense to split out scsi_allocate_pdu(), iscsi_pdu_set_pduflags(), etc. into something that can be easily consumed by iscsi-test-cu.

**Comment by sahlberg** [comment]
Sure,  that sounds like a good idea.   Do you have a patch?

**Comment by ddiss** [comment]
> Sure,  that sounds like a good idea.   Do you have a patch?

Not yet, was just checking whether it'd be an acceptable approach. I'll take that as a yes :)

**Comment by ddiss** [comment]
I've pushed changes which add a libiscsipriv convenience library for the test-tool to https://github.com/ddiss/libiscsi/tree/libiscsipriv . These are based atop the existing https://github.com/sahlberg/libiscsi/pull/299 PR.
I'll do some further testing and submit.

**Comment by ddiss** [comment]
Merged, closing...
