### ISSUE TITLE
Multiple definition errors in test-tool

### ISSUE THREAD

**Issue by bryceharrington** [sahlberg/libiscsi#340]
Following a cherry-pick of #308 "attribute_packed.patch" to resolve a multiple-definition error with gcc10, Debian and Ubuntu CI's are also seeing "multiple defintion" errors in the test-tool code:

https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/libiscsi.html
https://buildd.debian.org/status/package.php?p=libiscsi
https://launchpad.net/ubuntu/+source/libiscsi/1.19.0-2/+build/19774393

This is with:
  Kernel version: 4.15.0-112-generic
  gcc version: 10.2.0
  

/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:782: multiple definition of `local_iscsi_queue_pdu'; iscsi-test-cu.o:./test-tool/iscsi-support.h:782: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:63: multiple definition of `copy_aborted_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:63: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:62: multiple definition of `miscompare_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:62: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:61: multiple definition of `removal_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:61: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:60: multiple definition of `sanitize_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:60: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:59: multiple definition of `write_protect_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:59: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:58: multiple definition of `unsupp_desc_code_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:58: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:57: multiple definition of `too_many_desc_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:57: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:56: multiple definition of `param_list_len_err_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:56: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:55: multiple definition of `invalid_cdb_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:55: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:54: multiple definition of `lba_oob_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:54: first defined here
/usr/bin/ld: test_prefetch10_simple.o:./test-tool/iscsi-support.h:53: multiple definition of `no_medium_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:53: first defined here
/usr/bin/ld: test_prefetch10_beyond_eol.o:./test-tool/iscsi-support.h:54: multiple definition of `lba_oob_ascqs'; iscsi-test-cu.o:./test-tool/iscsi-support.h:54: first defined here

**Comment by bvanassche** [comment]
The `local_iscsi_queue_pdu` variable has been removed from the upstream libiscsi project. Please sync the Ubuntu version of libiscsi with the upstream version. See also commit dd17293bcc188dbefc420ee23b77bc9bb7c5e9a2.

**Comment by cpaelzer** [comment]
These commits all combined fix the issue around local_iscsi_queue_pdu:
dd17293b 2ae45ac1 77279dd4 c830a3b5 b705f9e5 fdc45fad 153ca193 575ba224 c067eef9 310e9ace 60a5856f

But the circular header definitions for `miscompare_ascqs` and others stay.
I'll dive through upstream master, but if you have a pointer that could be helpful please let me know.

**Comment by cpaelzer** [comment]
Most likely ea89dcdb which I'll try ...

**Comment by cpaelzer** [comment]
Yes with this on top as well it works to build the version currently in Ubuntu.

And in the next cycle (feature freeze atm) we can sync the new version.
