### ISSUE TITLE
Block Device Characteristics failure treated as test failure even though it is an optional command

### ISSUE THREAD

**Issue by nvenkataddn** [sahlberg/libiscsi#354]
In the iscsi-test-cu.c, inquiry is being issued with block device characteristics page and if the command fails with any error other than invalid opcode, it causes a test failure. However, block device characteristics page is an optional command and the target may not be supporting this inquiry. So as a fix moved the test out of the main test code and made it part of the inquiry test suites. 
[patch_inq_bdc.txt](https://github.com/sahlberg/libiscsi/files/6551568/patch_inq_bdc.txt)

**Comment by bvanassche** [comment]
Please submit a pull request instead of submitting patches as an attachment.

**Comment by nvenkataddn** [comment]
I have submitted a pull request at #355. Also created a patch for the 1.19 branch since the patch for master does not work with 1.19. 
[patch_inq_bdc_1.19.txt](https://github.com/sahlberg/libiscsi/files/6668461/patch_inq_bdc_1.19.txt)
