### ISSUE TITLE
test_async_write.c file has a minor error when compiling it in CentOS 7

### ISSUE THREAD

**Issue by tenderbulk** [sahlberg/libiscsi#356]
Dear Mr Sahlberg ，
There seems to be an error when I compiled  test asyn_write .c   as the following code section shows :
test_async_write.c:149:9: error: missing initializer for field ‘io_dispatched’ of ‘struct tests_async_write_state’ [-Werror=missing-field-initializers]
  struct tests_async_write_state state = { };

The  development software components are ：
   1  OS :  centos 7 .6 
   2 Cunit version :  CUnit-2.1-3.tar.bz2 , which is installed via source codes 
   3 GCC version : gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

My solution is like 
struct tests_async_write_state state = { };  
 --->
struct tests_async_write_state state;
memset (&state, 0 ,sizeof(tests_async_write_state));

At last, the minor error was found in my settings , and I have no idea if it exists in the other mainstream Linux system . 
Were I wrong , you kindly ignore the issues . 

thanks in advance 
the best

**Comment by bvanassche** [comment]
Is it possible to upgrade to CentOS 7.9 or 8.4? I'm not sure any other libiscsi users are using CentOS 7.6.

**Comment by tenderbulk** [comment]
thank you for answering , dear Sahlberg.  Actually , I checked that  gcc compiler version  might have a little bit impact on the compilation. Other linux system users did not meet the error before since they are using the latetest main stream Linux system. 
Yet，from my side, I prefer to change the codes locally using compatible coding line for GCC version as posted before.

Last , It is NICE that we can close the issue .  thank you for your time 

The best
