### ISSUE TITLE
uncertain as of how to make connection to target

### ISSUE THREAD

**Issue by JohnEridium** [sahlberg/libiscsi#373]
Hello,

I just installed libiscsi via home-brew on macOS Monterey 12.3, but I am not sure how to connect to a target. I set up a test target on a Debian 10 VM and verified with another VM that I can in fact connect to the target. 

On macOS however, I have not found any command line tools or UI apps after installing libicsi via homebrew. The only other approach I could think of was via the finder and the "connect to server" dialogue (cmd + k), but I had no success there either. Can anyone give me some guidance on how to use libiscsi to connect to a iSCSI target?

The addresses I tried entering in the "cmd + k" dialogue:
iscsi://192.168.2.79/iqn.myimac.network?target_user=john&target_password=doe
iscsi://john%doe@192.168.2.79/iqn.myimac.network

Here my config on the debian 10 target:

## nano /etc/tgt/conf.d/myimac.conf
<target iqn.myimac.network>

backing-store /dev/sdb
initiator-name iqn.myimac.network
incominguser john doe
</target>

The initiator config on the second VM was:

## removed the comment here to make the lines active, didn't touch the rest ##
node.session.auth.authmethod = CHAP 

node.session.auth.username = john
node.session.auth.password = doe

Any tips would be greatly appreciated.

**Comment by JohnEridium** [comment]
Update: I tried to manually install libiscsi and after a reboot, the iscsi-inq command appears to be (almost) working. But when I try to connect to the target, I get the following error:

`libiscsi:1 iscsi_service: POLLHUP, socket error. [iqn.test]
libiscsi:1 iscsi_service_reconnect_if_loggedin. Can not reconnect right now.
 [iqn.test]
libiscsi:1 iscsi_service failed with : iscsi_service_reconnect_if_loggedin. Can not reconnect right now.
 [iqn.test]
Login Failed. iscsi_service failed with : iscsi_service_reconnect_if_loggedin. Can not reconnect right now.`

The error appears no matter if CHAP auth is used or not (no user/password).

Commands used:

`iscsi-inq -d iscsi://john%doe@192.168.2.79:3260/iqn.myimac.network/1 `
`iscsi-inq iscsi://192.168.2.79/iqn.test/1 -d ` <-- Here the CHAP auth parameters from the targets were removed.

What am I doing wrong?

**Comment by JohnEridium** [comment]
Another Update:

I reinstalled the hombebrew version and now I'm getting a bit more info with my errors:


command: `export LIBISCSI_CHAP_USERNAME=john && export LIBISCSI_CHAP_PASSWORD=doe && sudo iscsi-inq iscsi://192.168.2.80/iqn.test.network/1 -d`

`libiscsi:1 iscsi_service: POLLHUP, socket error. [iqn.test.network]
libiscsi:1 iscsi_service_reconnect_if_loggedin. Can not reconnect right now.
 [iqn.test.network]
libiscsi:1 iscsi_service failed with : iscsi_service_reconnect_if_loggedin. Can not reconnect right now.
 [iqn.test.network]
Login Failed. iscsi_service failed with : iscsi_service_reconnect_if_loggedin. Can not reconnect right now.

libiscsi:1 1 memory blocks lost at iscsi_destroy_context() after 5 malloc(s), 11 realloc(s), 4 free(s) and 0 reused small allocations [iqn.test.network]`


I reinstalled the VM the iSCSI target is running on, therefore the changed IP. I confirmed again with another Debian VM that the iSCSI target is in fact working.

**Comment by JohnEridium** [comment]
Found the issue: I configured an initiator iqn at the target which obviously prevented the initiator from connecting properly.

**Comment by sahlberg** [comment]
It should work on macos, however, while this is a client, is is a
userspace / application client, so even when you manage to connect to
the target LUN, this LUN will not be visible to the actual operating
system.
It will only be visible to special applications that link to libiscsi
and access the LUN that way, I.e. you will not be able to have this
show up in the os or as a drive.
Special applications, like QEMU may have code that links directly with
libiscsi and make them available to use these target LUNs   but that
requires that the application will be specially written to use
libiscsi to access remote disks.
You will likely never be able to use libiscsi to attack the mac os to
a remore iscsi target. I imagine macos have native os level support
for this.
