### ISSUE TITLE
cannot modify scsi-lowlevel.c file

### ISSUE THREAD

**Issue by sallyjunjun** [sahlberg/libiscsi#380]
I tried to edit scsi-lowlevel.c file to fix some "dereference null return value" problems, but when I click "commit changes" button, it shows  ERR_EMPTY_RESPONSE error. This problem only shows in this file. I can modify other files. So I want to ask is there some protection for this file to prevent other users from editing.

**Comment by bvanassche** [comment]
Have you already tried to use git from the command line instead of using a graphical user interface?

**Comment by sallyjunjun** [comment]
I try with git, and the problem is solved. Thank you.
