### ISSUE TITLE
test-tool is not build

### ISSUE THREAD

**Issue by folkertvanheusden** [sahlberg/libiscsi#423]
When I run `./configure --enable-test-tool --enable-tests --enable-examples` (and make), the `iscsi-test` is not build (nor is `iscsi-test-cu` build).

**Comment by folkertvanheusden** [comment]
Ah, libcunit1-dev was not installed. that is not mentioned in the docs?

**Comment by sahlberg** [comment]
Doc has been updated.  Thanks!
